version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database

  redis:
    image: redis

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
